CREATE DATABASE IF NOT EXISTS `vxrp` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `vxrp`;

CREATE TABLE IF NOT EXISTS `player_ucp` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `UCP` VARCHAR(24) NOT NULL,
    `IP` VARCHAR(16) NOT NULL DEFAULT '',
    `Password` VARCHAR(65) NOT NULL,
    `Salt` VARCHAR(17) NOT NULL DEFAULT '',
    `Admin` TINYINT(3) NOT NULL DEFAULT 0,
    `Register_Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Last_Login` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UCP` (`UCP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `player_characters` (
    `pID` INT(11) NOT NULL AUTO_INCREMENT,
    `Char_UCP` VARCHAR(24) NOT NULL,
    `Char_Name` VARCHAR(24) NOT NULL,
    `Char_IP` VARCHAR(16) NOT NULL DEFAULT '',
    `Char_Level` INT(11) NOT NULL DEFAULT 1,
    `Char_Money` INT(11) NOT NULL DEFAULT 5000,
    `Char_BankMoney` INT(11) NOT NULL DEFAULT 0,
    `Char_Skin` INT(11) NOT NULL DEFAULT 26,
    `Char_Gender` TINYINT(1) NOT NULL DEFAULT 0,
    `Char_Age` TINYINT(3) NOT NULL DEFAULT 18,
    `Char_Health` FLOAT NOT NULL DEFAULT 100.0,
    `Char_Armor` FLOAT NOT NULL DEFAULT 0.0,
    `Char_PosX` FLOAT NOT NULL DEFAULT 1958.3783,
    `Char_PosY` FLOAT NOT NULL DEFAULT 1343.1572,
    `Char_PosZ` FLOAT NOT NULL DEFAULT 15.3746,
    `Char_PosA` FLOAT NOT NULL DEFAULT 270.1425,
    `Char_IntID` INT(11) NOT NULL DEFAULT 0,
    `Char_WID` INT(11) NOT NULL DEFAULT 0,
    `Char_RegisterDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Char_LastLogin` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`pID`),
    UNIQUE KEY `Char_Name` (`Char_Name`),
    KEY `Char_UCP` (`Char_UCP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
